Elbette! Aşağıda, Deep Learning bölümünde seni bekleyen tüm konuları tek bir bütün olarak ele alarak, sade, sistemli ve vizyon kazandırıcı bir şekilde özetledim:

---

## 🧠 Derin Öğrenme (Deep Learning) Bölümünde Seni Neler Bekliyor?

Bu bölüm, klasik makine öğrenmesinden çıkarak **insan beyninden ilham alan bir yapay öğrenme sistemi olan “Yapay Sinir Ağları (ANN)”** ile tanışmanı sağlayacak. Hem **teorik temelleri** öğreneceksin hem de **TensorFlow kullanarak gerçek bir projeyi sıfırdan inşa edeceksin**.

---

### 🎯 1. Derin Öğrenmenin Temelleri

* Derin öğrenme neden önemlidir? Hangi sorunları klasik yöntemlerle çözemeyiz?
* **Nöronlar**, **katmanlar**, **ağırlıklar**, **aktivasyon fonksiyonları**, **geri yayılım (backpropagation)** gibi temel yapı taşlarını öğreneceksin.
* **Yapay Sinir Ağı (ANN)** nasıl çalışır, nasıl öğrenir, hangi katmanlar ne işe yarar?
* En çok kullanılan **aktivasyon fonksiyonlarının** (ReLU, Sigmoid, Tanh) mantığını öğrenecek ve ne zaman hangisini kullanacağını anlayacaksın.
* **Gradient Descent** gibi optimizasyon tekniklerinin arkasındaki matematiksel mantığı göreceksin (ama korkma, sade anlatılacak).
* **Stochastic**, **batch** ve **mini-batch** gradient descent farklarını kavrayacaksın (performans ve stabilite açısından).

---

### 🧪 2. Uygulamalı Proje: Müşteri Kaybı (Churn Prediction)

Bir bankanın verilerini kullanarak şunu tahmin etmeye çalışacaksın:

> “Bu müşteri bankayı terk eder mi?”

**Bu gerçek dünya problemine ANN ile çözüm üreteceksin.** Aşamalar şöyle:

#### 📌 Veri Ön İşleme

* Kategorik verileri sayısal hale getirme (encoding)
* Özellikleri aynı ölçekte getirme (scaling)
* Eğitim ve test setine bölme

#### 🏗️ Model Kurma (TensorFlow)

* `Sequential` model ile **katman katman** ANN oluşturacaksın
* `Dense` (tam bağlı) katmanları yapılandıracaksın
* Aktivasyon fonksiyonlarını seçeceksin

#### ⚙️ Model Eğitimi

* Kayıp fonksiyonu: `binary_crossentropy` (çünkü çıktı: evet/hayır)
* Optimizasyon: `adam` (pratikte en iyi sonuçları verir)
* Epoch ve batch size gibi eğitim parametrelerini seçeceksin

#### 🔍 Değerlendirme

* Tahmin sonuçlarını `confusion_matrix` ile analiz edeceksin
* Doğruluk oranını (`accuracy`) ölçeceksin
* Gerekirse model üzerinde iyileştirme yapabileceksin

---

### 💡 Öğreneceklerinin Özet Haritası

| Alan                     | Öğreneceğin Şey                                        |
| ------------------------ | ------------------------------------------------------ |
| Yapay Sinir Ağları (ANN) | Temel yapı, öğrenme mantığı, aktivasyon                |
| TensorFlow/Keras         | Derin öğrenme modellerini kurma ve eğitme              |
| Optimizasyon             | Gradient descent, learning rate kavramları             |
| Aktivasyon Fonksiyonları | ReLU, Sigmoid, Tanh ne işe yarar, ne zaman kullanılır? |
| Eğitim Süreci            | Epoch, batch size, loss, accuracy                      |
| Gerçek Dünya Projesi     | Müşteri kaybı tahmini – sıfırdan sona                  |

---

## ✅ Bu Bölümden Çıkarken Neyi Başarmış Olacaksın?

* Yapay sinir ağlarının nasıl çalıştığını içselleştirmiş olacaksın
* TensorFlow ile sıfırdan bir ANN kurabilecek seviyeye geleceksin
* Parametreleri oynayarak modelin performansını iyileştirme becerisi kazanacaksın
* Derin öğrenmeye teorik ve pratik bir giriş yapmış olacaksın
* Artık CNN, RNN, LSTM gibi daha ileri yapay sinir ağı türlerine hazır olacaksın

---

Eğer istersen bu ANN projesini birlikte adım adım koda dökebilir, kendi verilerini test edebiliriz.
Hazırsan “Churn Prediction” uygulamasına geçebiliriz! 🚀


Elbette, bu çok önemli temel maddeleri senin için sade, net ve anlaşılır şekilde açıklayayım. Bunlar derin öğrenmeyi anlaman için olmazsa olmaz taşlardır. Her maddeyi ayrı başlık altında detaylandıralım:

---

## 🧠 1. Derin Öğrenme Neden Önemlidir?

### ❓ Klasik Yöntemler Nerede Yetersiz Kalır?

Klasik Makine Öğrenmesi (ML) modelleri (logistic regression, decision tree, SVM) şu durumlarda zorlanır:

* **Görüntü tanıma** (el yazısı, yüz tanıma)
* **Doğal dil işleme** (cümle çevirisi, duygu analizi)
* **Ses tanıma** (asistanlar, otomatik altyazı)
* **Veri çok büyük ve karmaşıksa** (örneğin: milyonlarca piksel veya kelime içeren veriler)

📌 **Derin Öğrenme**, büyük ve karmaşık veri setlerinden otomatik olarak **özellik çıkarımı yaparak** yüksek başarı sağlar.

---

## 🧠 2. Temel Yapı Taşları

### 🔹 Nöron (Artificial Neuron)

* İnsan beynindeki nöronlardan esinlenir.
* Girişleri alır (x₁, x₂, …), ağırlıklarla çarpar (w₁, w₂, …), toplar → aktivasyon fonksiyonuna sokar.

👉 Formül:

```plaintext
z = w₁·x₁ + w₂·x₂ + … + b
a = activation(z)
```

---

### 🔹 Katmanlar (Layers)

* **Input Layer:** Verinin modele ilk girdiği yer
* **Hidden Layers:** Öğrenme burada gerçekleşir, özellik çıkarımı yapılır
* **Output Layer:** Tahmin veya sınıflandırma yapılır

---

### 🔹 Ağırlıklar (Weights) ve Bias

* **Ağırlık (w):** Girdilerin önemini belirler
* **Bias (b):** Modelin daha esnek olmasını sağlar (tahmini kaydırır)

---

### 🔹 Aktivasyon Fonksiyonları

Nöronun çıkışına “non-linearity” katar. En yaygınları:

| Fonksiyon   | Özellik                         | Ne zaman kullanılır?                             |
| ----------- | ------------------------------- | ------------------------------------------------ |
| **Sigmoid** | 0–1 arası çıktı                 | Binary classification                            |
| **Tanh**    | -1 ile 1 arası çıktı            | Orta ölçekli sinyaller                           |
| **ReLU**    | 0’dan küçükse 0, büyükse aynısı | Derin ağlarda en sık kullanılan, hızlı ve etkili |

Threshold function (eşik fonksiyonu) aslında **aktivasyon fonksiyonlarının en basit ve en eski hali** diyebiliriz.
Sana hem tanımını hem mantığını hem de neden modern sinir ağlarında artık pek kullanılmadığını anlatayım.

---


---

## 🧠 **Aktivasyon Fonksiyonları Özeti**

| **Fonksiyon**               | **Formül**                        | **Aralık**      | **Avantajları**                                   | **Dezavantajları**                          | **Ne Zaman Kullanılır?**                          |
| --------------------------- | --------------------------------- | --------------- | ------------------------------------------------- | ------------------------------------------- | ------------------------------------------------- |
| **Threshold (Step)**        | `0 / 1`                           | {0,1}           | Basit karar mantığı                               | Türev yok, öğrenme zor                      | Perceptron, teorik anlatımlar                     |
| **Sigmoid**                 | `1 / (1 + e^-x)`                  | (0,1)           | Olasılık yorumu kolay, binary sınıflandırmada iyi | Büyük x değerlerinde **vanishing gradient** | Çıkış katmanı (binary classification)             |
| **Tanh**                    | `(e^x - e^-x) / (e^x + e^-x)`     | (-1,1)          | Sıfır merkezli, genelde sigmoid’den daha iyi      | Yine vanishing gradient                     | Gizli katmanlar (küçük ölçekli modellerde)        |
| **ReLU**                    | `max(0, x)`                       | \[0,∞)          | Hızlı, vanishing gradient az                      | Negatiflerde “dead ReLU” sorunu             | Gizli katmanlarda varsayılan tercih               |
| **Leaky ReLU**              | `x (x>0), αx (x<0)`               | (-∞,∞)          | Dead ReLU çözümü                                  | α parametresi ayar gerektirir               | Negatif bilgiyi korumak istediğinde               |
| **Parametric ReLU (PReLU)** | `x (x>0), αx (x<0)` (α öğrenilir) | (-∞,∞)          | Negatif eğim öğrenilir, daha esnek                | Fazla parametre, aşırı öğrenme riski        | Özel derin ağ tasarımlarında                      |
| **Softmax**                 | `e^(xi) / Σ e^(xj)`               | (0,1), toplam=1 | Çok sınıflı (multi-class) olasılık tahmini        | Hesap maliyeti var                          | Çıkış katmanı (multi-class classification)        |
| **Swish** *(Google)*        | `x * sigmoid(x)`                  | (-∞,∞)          | Derin ağlarda iyi sonuçlar                        | ReLU kadar hızlı değil                      | Son yıllarda bazı CNN ve Transformer modellerinde |

---

## 🎯 **Fonksiyon Seçim Rehberi**

* **Binary classification (çıkış katmanı)** → **Sigmoid**
* **Multi-class classification (çıkış katmanı)** → **Softmax**
* **Gizli katmanlarda genel kullanım** → **ReLU** (veya türevleri: Leaky ReLU, PReLU)
* **Küçük ağlar, klasik modeller** → **Tanh**
* **Teorik veya basit mantık** → **Threshold**

---

💡 **Özet Mantık:**

* **Gizli katmanlarda ReLU** → hızlı, kararlı, modern standart
* **Çıkışta Sigmoid / Softmax** → sınıflandırma tipine göre
* **Alternatifler (Leaky, Swish)** → özel durumlar veya ReLU’nun eksiklerini kapatmak için

---

Eğer istersen sana bunların **grafiklerini tek tabloda** çizerim, böylece hangi fonksiyonun hangi bölgede nasıl davrandığını **görsel olarak** anında kavrayabilirsin.
İster misin onu yapayım?


## 🎯 Günümüzdeki Durum

* Modern sinir ağlarında **Sigmoid**, **Tanh** veya **ReLU** kullanılır
* Çünkü bu fonksiyonlar **sürekli** ve **türevlenebilir**
* Threshold function genellikle **mantıksal devre benzetimlerinde** veya **teorik anlatımlarda** kullanılır

---

💡 **Kısacası:** Threshold function = “aç/kapa” düğmesi gibi.
Modern deep learning = “ışık dimmeri” gibi (parlaklığı kademeli ayarlayabilir).

---

Eğer istersen ben sana **threshold function ile sigmoid farkını grafikle** gösteririm, o zaman neden artık kullanılmadığını çok net anlarsın.
İster misin onu yapayım?



---



## 🧠 3. ANN Nasıl Öğrenir?

### 🔄 İleri Besleme (Forward Propagation)

Veri girişten çıkışa doğru akar, her katman veriyi işler ve bir çıktı üretir.

### 🔁 Geri Yayılım (Backpropagation)

Modelin yaptığı hata (loss) hesaplanır ve bu hata **ağırlıklara geri yayılır**. Böylece model kendi hatalarından öğrenir.

---

## 🧠 4. Gradient Descent Nedir?

> Amaç: Tahminle gerçek sonuç arasındaki farkı (hata) **minimuma indirmek**.

Gradient descent, bir "tepe inişi" algoritmasıdır. Hata fonksiyonunun eğimine bakarak ağırlıkları her adımda **azıcık değiştirir**.

 Gradient Descent’in temel amacı aslında tek cümleyle şöyle özetlenir:

> **Bir modelin hatasını (loss) en aza indirmek için ağırlıkları adım adım en uygun değerlere getirmek.**

Bunu biraz açalım:

---

## 🧠 **Temel Mantık**

* Her makine öğrenmesi / derin öğrenme modelinde bir **loss function (hata fonksiyonu)** vardır.
  Örneğin:

  * Regresyonda → MSE (Mean Squared Error)
  * Sınıflandırmada → Cross-Entropy Loss
* Bu loss fonksiyonu, modelin tahminleri ile gerçek değerler arasındaki farkı ölçer.
* Amaç: **Loss’u mümkün olan en küçük değere getirmek** ✅

---

## ⛰️ **Eğim İnişi (Gradient Descent) Benzeri Benzetme**

* Kendini **sisli bir dağın tepesinde** düşün.
* Hedefin **en alttaki vadiye** (minimum hata noktası) inmek.
* Ama etrafı göremiyorsun → sadece **bulunduğun yerdeki eğimi** hissedebiliyorsun.
* O eğim yönünde **küçük adımlar atarak** aşağıya inersin.
* İşte **gradient descent** tam olarak bu.

---

## 🔢 **Nasıl Çalışır?**

1. **Ağırlıkları başlat** (rastgele veya belirli bir başlangıç değeriyle)
2. **Loss fonksiyonunu hesapla**
3. Loss fonksiyonunun **türevi (gradient)** ile eğimi bul
4. **Eğim yönünde ters tarafa** küçük bir adım at
5. Tekrar loss hesapla ve devam et → convergence (yakınsama) olana kadar

---

## ⚙️ **Formül**

```
w_new = w_old - η * ∂Loss/∂w
```

* `η` (**learning rate**): Adım büyüklüğü
* `∂Loss/∂w`: Loss fonksiyonunun ağırlıklara göre türevi (gradient)

---

## 🎯 **Amacı**

* Loss fonksiyonunu **minimum** yapmak
* Doğru ağırlıkları (w) ve bias değerlerini bulmak
* Modelin doğru tahminler yapabilmesini sağlamak

---

💡 **Özet:**
Gradient descent, yapay sinir ağları dahil tüm optimizasyon tabanlı modellerin **öğrenme motoru**dur.
Loss fonksiyonu “yol haritası” gibidir, gradient descent ise seni **en kısa ve doğru yoldan minimum hataya** götürmeye çalışan bir rehberdir.

🔍 Yani: Hata küçükse, ağırlık az değişir. Hata büyükse, daha çok değişir.

### 🔸 Learning Rate

* Ağırlıkların ne kadar değişeceğini belirler.
* Çok büyük → zıplar, öğrenemez.
* Çok küçük → öğrenme yavaş olur.

---

## 🧠 5. Stochastic vs Batch vs Mini-Batch Gradient Descent

| Tür               | Açıklama                                | Avantaj                  | Dezavantaj               |
| ----------------- | --------------------------------------- | ------------------------ | ------------------------ |
| **Batch GD**      | Tüm veri setiyle bir güncelleme         | Dengeli                  | Büyük veride yavaş       |
| **Stochastic GD** | Her veri noktasıyla bir güncelleme      | Hızlı, çeşitlilik sağlar | Gürültülü, dengesiz      |
| **Mini-Batch GD** | Küçük gruplarla güncelleme (en yaygını) | Hem hızlı hem dengeli    | Ek parametre: batch size |

Mini-batch genelde 32, 64, 128 gibi boyutlarda kullanılır ve derin öğrenmede **endüstri standardı**dır.

---

## ✅ Özetle

| Konu             | Ne Öğrenirsin?                            |
| ---------------- | ----------------------------------------- |
| Derin Öğrenme    | Klasik ML’in ötesine geçmeyi              |
| Nöron / Katman   | Veri işlenme mantığını                    |
| Aktivasyonlar    | Modelin öğrenme kapasitesini arttırmayı   |
| Gradient Descent | Modelin nasıl "kendini geliştirdiğini"    |
| GD Türleri       | Verimlilik ve hız açısından seçim yapmayı |

---

İstersen şimdi bu temel bilgilerle birlikte ANN mimarisini kodla nasıl kuracağımızı adım adım geçebiliriz. Ya da bu maddelerde anlamadığın bir yer varsa detaylandıralım. Hangisiyle ilerleyelim?


# Örnek Çalışma 
Bankadaki müşteri profillerinden kişinin bankadan ayrılıp ayrılmayacağına bakacaz

# Kütüphaneleri dahil ediyoruz

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.11.1'

## Part 1 - Data Preprocessing

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values #kredi skorunda tahmini maaşına kadar olanı alıyoruz
y = dataset.iloc[:, -1].values #son sütun

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data
Label Encoding the "Gender" column

In [13]:
from sklearn.preprocessing import LabelEncoder #2 cinsiyet olduğundan 0-1 olarak encod ediyoruz
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [14]:
print(X)

[[1.0 0.0 0 ... 1 1 101348.88]
 [0.0 0.0 1 ... 0 1 112542.58]
 [1.0 0.0 0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0 ... 0 1 42085.58]
 [0.0 1.0 0 ... 1 0 92888.52]
 [1.0 0.0 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [16]:
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling önemli derin öğrenme için

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN
### Initializing the ANN

In [20]:
ann = tf.keras.models.Sequential() #sıralı katmanlı sinir ağı kuruyoruz

### Adding the input layer and the first hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [22]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [23]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # 0 veya 1

## Part 3 - Training the ANN
### Compiling the ANN

In [26]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) #adam gd burada

### Training the ANN on the Training set

In [27]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6317 - accuracy: 0.6870
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4856 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4429 - accuracy: 0.8010
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4298 - accuracy: 0.8100
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4241 - accuracy: 0.8121
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4208 - accuracy: 0.8150
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4183 - accuracy: 0.8149
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4160 - accuracy: 0.8173
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4140 - accuracy: 0.8177
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4116 - accura

## Part 4 - Making the predictions and evaluating the model
### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [41]:
print(X[0])
print(len(X[0]))
print(sc.transform([[1, 0, 1, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
print(ann.predict(sc.transform([[1, 0, 0, 1, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5) 
#0.5 üstü ise true altı ise false verecek tahmin için

[1.0 0.0 1.0 0 619 0 42 2 0.0 1 1 1 101348.88]
13
[[ 0.5698444  -0.5698444   0.98560362 -0.57369368 -0.52111599  0.91601335
   0.10961719 -0.68538967 -0.2569057   0.8095029   0.64259497  0.9687384
  -0.87203322]]
1/1 [==============================] - 0s 31ms/step
[[False]]


Bu nedenle, ANN modelimiz bu müşterinin bankada kalacağını öngörüyor!

**Önemli not 1:** Tüm özellik değerlerinin çift köşeli parantez içinde girildiğine dikkat edin. Bunun nedeni, "tahmin" yönteminin girdilerinin biçimi olarak her zaman 2 boyutlu bir dizi beklemesidir. Değerlerimizi çift köşeli parantez içine almak, girdiyi tam olarak 2 boyutlu bir dizi haline getirir.

**Önemli not 2:** Ayrıca, "Fransa" ülkesinin son sütunda bir dize olarak değil, ilk üç sütunda "1, 0, 0" olarak girildiğine dikkat edin. Bunun nedeni, tahmin yönteminin elbette eyaletin tek sıcak kodlanmış değerlerini beklemesi ve X özellik matrisinin ilk satırında gördüğümüz gibi, "Fransa"nın "1, 0, 0" olarak kodlanmış olmasıdır. Bu değerleri ilk üç sütuna dahil etmeye dikkat edin, çünkü kukla değişkenler her zaman ilk sütunlarda oluşturulur.

In [44]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
#sol tarafa gerçek sonuçkar sağ tarafı tahmin edilenler

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)
#%86 doğru kontrol ediyor
#1523 müşterinin kalacağını doğru tahmin ediyor
#203 müşterinin kalmayacağını doğru tahmin ediyor
#72 kişiyi ayrılacak diye yanlış hesaplıyor
#202 müşteriyi kalacak diyerek yanlış hesaplıyor

[[1523   72]
 [ 202  203]]


0.863

### 