# Veri önişleme toolları

## 1-Kütüphane aktarımı

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## 2-Veriseti Aktarımı

In [6]:
dataset = pd.read_csv("Data.csv")
# iloc index locations demek sırası ile burada tüm satırlar dedik ilk başta sonrasında ilk üç sütun dedik x,y olarak düşün, 
# features yani özellikler verilerdeki burada ülke yaş maaş bu sebepten veriki 3 sütunu alıyoruz
x = dataset.iloc[:,:-1].values 
# depending variable yani tahmin etmeye çalıştığımı değer burada satın alınıp alınmadığı yes/no şeklinde son sütünu alıyoruz veride
y = dataset.iloc[:,-1].values #sadece son satırı alır

In [12]:
print(x) #burada np array olarak oluşturdu unutma pd dataframe değil

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [14]:
print(y) #son sütun

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## 3-Eksik verilerin üstesinden gelmek

In [16]:
from sklearn.impute import SimpleImputer
#Eksik Salary satır kısmına o sütun ortalama değerini eklemek
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
#oluşturduğumuz yöntemi ekliyoruz veriye
imputer.fit(x[:,1:3]) #yaş ve salary satırlarına ortalama değerleri ekleyecek
x[:,1:3] = imputer.transform(x[:,1:3]) #bu veriyi yeni verilerei ekliyor tam anlamı ile

In [17]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Kategorik verilerin kodlanması - Encoding categorical data

### Bağımsız değişlenlerin kodlanması- Encoding the Indepentent variable

In [26]:
#Mevcut veri için konuşacak olursak makina öğrenimi 
#sayısal değer ister bu yüzden ülke isimlerini sayısala çeviricez
#burada unutma kategorik olan veriler için yapıyoruz
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#ülke isimlerini encodluyoruz
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x)) #np array yapma sebebi birden fazla sütun var

In [27]:
print(x) # dikkat edilirse ct de belirlediğimiz 0 sütununda olan ülk isimleri sadete encodlanacak

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


### Bağımlı değişkenlerin kodlanması - Encoding the dependent variable

In [30]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y= le.fit_transform(y) #tek sütunluk bir veri olduğu için

In [31]:
print(y) #satır etiketini 0 ve 1 olarak encodladık diyebiliriz

[0 1 0 0 1 1 0 1 0 1]


## Verisetini Test ve Eğitim Olarak iki parçaya ayırmak
## Splitting the dataset into the Training set and Test Set

In [37]:
#en popüler olar sklearn train test split fonksiyonu veriyi bölmek için
from sklearn.model_selection import train_test_split
#random_state rastgele veri almasını sağlar 0.2 yüzde 20 olarak test ayırmasını sağlar
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size= 0.2,random_state= 1)

In [38]:
print(X_train)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [39]:
print(X_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [40]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [41]:
print(y_test)

[0 1]


## Özellik Ölçeklendirmesi
## Feature Scaling

✅ Neden fit_transform() sadece eğitim verisine uygulanır?
Çünkü:

fit() fonksiyonu ölçeklendirme (scaling) parametrelerini hesaplar:

    Örneğin StandardScaler için: ortalama (mean) ve standart sapma (std)

    MinMaxScaler için: min ve max değer

Eğer bu parametreleri hem eğitim hem test verisinden birlikte hesap edersen, test verisinin gelecekteki dağılım bilgisi modele sızar. Bu da:
❌ Data Leakage (Veri Sızıntısı) problemine yol açar.

Bu da modelin sahte bir başarıya ulaşmasına sebep olur, çünkü model test verisinin dağılımını önceden öğrenmiş olur.
🔄 Doğru yaklaşım:

    scaler.fit_transform(X_train)
    👉 Eğitim verisinden parametreleri öğren ve uygula

    scaler.transform(X_test)
    👉 Aynı parametreleri (mean, std, min, max vs.) test verisine uygula

Bu şekilde model, hiç görmediği veriye karşı doğru şekilde test edilir.

In [42]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
#standardscaleri sadece burada örnek vermek gerekirse kullanıcı yaşlarına maaşlarına uygulamak anlamlı olur
#çünkü onehot kodlaması yaptığımız ülkeler için saçma sonuçlar verir
#ülke kodlamalarını korumamız lazım burada
X_train[:,3:] = scaler.fit_transform(X_train[:,3:]) #ilk sütundaki değerlerin ortalamalarını alır sonra formüle uygular
X_test[:,3:] = scaler.transform(X_test[:,3:])

In [43]:
print(X_train)

[[1.0 0.0 0.0 1.2909944487358056 -0.19159184384578545 -1.0781259408412425]
 [1.0 0.0 1.0 -0.7745966692414834 -0.014117293757057777
  -0.07013167641635372]
 [0.0 1.0 0.0 -0.7745966692414834 0.566708506533324 0.633562432710455]
 [1.0 0.0 0.0 1.2909944487358056 -0.30453019390224867
  -0.30786617274297867]
 [1.0 0.0 0.0 1.2909944487358056 -1.9018011447007988 -1.420463615551582]
 [0.0 1.0 0.0 -0.7745966692414834 1.1475343068237058 1.232653363453549]
 [1.0 0.0 1.0 -0.7745966692414834 1.4379472069688968 1.5749910381638885]
 [0.0 1.0 0.0 -0.7745966692414834 -0.7401495441200351 -0.5646194287757332]]


In [44]:
print(X_test)

[[1.0 0.0 1.0 -0.7745966692414834 -1.4661817944830124 -0.9069571034860727]
 [0.0 1.0 0.0 -0.7745966692414834 -0.44973664397484414 0.2056403393225306]]
